from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch
from datetime import datetime
import os


def generate_pdf(df, job_title="Not Specified"):
    os.makedirs("results", exist_ok=True)
    pdf_name = os.path.join("results","Candidate_Ranking_Report.pdf")

    doc = SimpleDocTemplate(
        pdf_name,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    heading_style = styles["Heading2"]

    normal_style = styles["Normal"]

    elements = []

    # ----------------------------------------------------
    # Title
    # ----------------------------------------------------

    elements.append(
        Paragraph(
            "AI Resume Screening & Candidate Ranking Report",
            title_style
        )
    )

    elements.append(Spacer(1, 0.25 * inch))

    # ----------------------------------------------------
    # Report Information
    # ----------------------------------------------------

    current_date = datetime.now().strftime("%d %B %Y")

    elements.append(
        Paragraph(
            f"<b>Generated On:</b> {current_date}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"<b>Job Description:</b> {job_title}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"<b>Total Candidates:</b> {len(df)}",
            normal_style
        )
    )

    elements.append(Spacer(1, 0.30 * inch))

    # ----------------------------------------------------
    # Ranking Table
    # ----------------------------------------------------
    df = df.copy()
    df["Recommendation"] = (
        df["Recommendation"]
        .str.replace("⭐", "", regex=False)
        .str.replace("✅", "", regex=False)
        .str.replace("⚠", "", regex=False)
        .str.replace("❌", "", regex=False)
        .str.strip()
    )

    # Format Match Score to exactly 2 decimal places
    df["Match Score"] = df["Match Score"].apply(lambda x: f"{x:.2f}")

    data = [list(df.columns)]

    for _, row in df.iterrows():
        data.append(row.tolist())

    table = Table(data, repeatRows=1)

    table.setStyle(
        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 11),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),

            ("FONTSIZE", (0, 1), (-1, -1), 10),

        ])
    )

    elements.append(table)

    elements.append(Spacer(1, 0.40 * inch))

    # ----------------------------------------------------
    # Footer
    # ----------------------------------------------------

    elements.append(
        Paragraph(
            "<b>Generated by:</b> AI Resume Screening & Candidate Ranking System",
            heading_style
        )
    )

    elements.append(
        Paragraph(
            "Version 1.0",
            normal_style
        )
    )

    doc.build(elements)

    return pdf_name